NumPy - Numerical Python
Advantage of NumPy arrays:
1.   Allows Several Mathematical Operation
2.   Faster Operation

In [29]:
import numpy as np

In [30]:
from time import process_time

In [31]:
#without numpy
python_list= [i for i in range(10000)]
start_time=process_time()
python_list=[i+5 for i in python_list]
end_time=process_time()
print(end_time-start_time)

0.0020999999999999908


In [ ]:
#with numpy
np_arrary=np.array([i for i in range(10000)])
start_time=process_time()
np_arrary+=5
end_time=process_time()
print(end_time-start_time)

NumPy Arrays


In [39]:
a=np.array([(1,2,3),(4,5,6)])
print(a)

c=np.array([(1,2,3),(4,5,6)],dtype=float)
print(c)

a.shape


[[1 2 3]
 [4 5 6]]
[[1. 2. 3.]
 [4. 5. 6.]]


(2, 3)

Creating Random Values in NumPy arrays


In [51]:
a=np.ones((3,4))
print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [49]:
b=np.zeros((3,4))
print(b)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [50]:
c=np.random.random((3,4))
print(c)

[[0.33243977 0.13912413 0.09711681 0.87892896]
 [0.12139099 0.99506686 0.72178304 0.4595452 ]
 [0.05228776 0.24272785 0.14045929 0.56304132]]


In [53]:
d=np.random.randint(90,100,(3,4))
print(d)

[[91 95 99 96]
 [94 97 96 91]
 [96 94 97 90]]


Analaysis a NumPy array

In [56]:
c=np.random.randint(10,90,(5,5))
print("Array:")
print(c)
print("Shape:")
print(c.shape)
print("Dimention:")
print(c.ndim)
print("Size:")
print(c.size)
print("Datatype:")
print(c.dtype)
print("Bytes:")
print(c.nbytes)
print("Total Item:")
print(c.itemsize)
print("Location:")
print(c.data)
print("Flags:")
print(c.flags)

Array:
[[42 13 82 20 29]
 [66 79 69 29 43]
 [21 48 85 78 77]
 [67 83 50 26 65]
 [21 88 62 58 22]]
Shape:
(5, 5)
Dimention:
2
Size:
25
Datatype:
int64
Bytes:
200
Total Item:
8
Location:
Flags:
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



Array MAnipulation


In [60]:
#Array Transpose
c=np.random.randint(10,90,(2,3))
print("Array:")
print(c)
print("Shape:")
print(c.shape)
trans=np.transpose(c)
print("Transpose Array:")
print(trans)
print("Transpose Shape:")
print(trans.shape)

Array:
[[25 19 31]
 [58 33 28]]
Shape:
(2, 3)
Transpose Array:
[[25 58]
 [19 33]
 [31 28]]
Transpose Shape:
(3, 2)


In [63]:
#Array Transpose 2
c=np.random.randint(10,90,(2,3))
print("Array:")
print(c)
print("Shape:")
print(c.shape)
trans=c.T
print("Transpose Array:")
print(trans)
print("Transpose Shape:")
print(trans.shape)


Array:
[[18 62 22]
 [41 25 68]]
Shape:
(2, 3)
Transpose Array:
[[18 41]
 [62 25]
 [22 68]]
Transpose Shape:
(3, 2)


In [66]:
#reshape
c=np.random.randint(10,90,(2,3))
print("Array:")
print(c)
print("Shape:")
print(c.shape)
res=np.reshape(c,(3,2))
print("Reshape Array:")
print(res)
res.shape

Array:
[[25 70 18]
 [65 70 46]]
Shape:
(2, 3)
Reshape Array:
[[25 70]
 [18 65]
 [70 46]]


(3, 2)